### DISCUSSION TITLE
Adding support guide for mysql with docker

### DISCUSSION THREAD

**Discussion by nakulnagariy** [brocoders/nestjs-boilerplate#1664] [Show and tell]
_This could be just basics to many of you but it was a lot of exploration for me so just wanted to share my work._

If you were wanted to go with MySQL instead of `postgres` DB, changes can be done after you follow the complete guide given [here](https://github.com/brocoders/nestjs-boilerplate/blob/main/docs/introduction.md).

Once you have done all the steps you should have a running app.
![image](https://github.com/user-attachments/assets/ec60b61a-65e6-43e2-9bcf-72dad4c8a9fa)

If you make it till here, it just requires a couple of changes to switch from `postgres` to `MySql`.

**change the `docker-compose.yml` to the following:**

just make sure, you have the the available port for sql if not change it to something else **`eg. 3333`**

`.env`

```env
DATABASE_TYPE=mysql
DATABASE_HOST="localhost"
DATABASE_PORT=3333
DATABASE_USERNAME=root
DATABASE_PASSWORD="mysqlpass"
DATABASE_NAME=legalyatra_services
```

`docker-compose.yml`

```yml
services:
  mysql:
    image: mysql
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ~/db/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
```

After you done with the above setup try to run the docker with the following script:

```bash
docker compose up -d mysql adminer maildev
```

your all three services should be running like below.

![image](https://github.com/user-attachments/assets/73e10325-66ed-46ca-a0c5-45791ef0750f)

Once your services are up and running, you almost half way through already.

Now install Mysql client.
```bash
npm i mysql2 --save
```

**Now delete the already generated migration file. and generate a new one with below script.**

```bash
npm run migration:generate -- src/database/migrations/newMigration --pretty=true
```

Run migrations

   ```bash
   npm run migration:run
   ```

Run seeds

   ```bash
   npm run seed:run:relational
   ```

Run app in dev mode

   ```bash
   npm run start:dev
   ```

Open <http://localhost:3000>

To setup Adminer

Open the running port in your browser.
Open <http://localhost:8080>

![image](https://github.com/user-attachments/assets/f4b86daa-d93f-4ae9-a9e3-3c29bb3bba9d)

Running App SS:
![image](https://github.com/user-attachments/assets/5dc0609d-5f6d-4176-918d-1744906f4f88)
![image](https://github.com/user-attachments/assets/ff2201a6-d834-4c8b-9ab7-b9413a0a95c1)

Now you're all set for your project.
